name: Bulid

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Spellcheck
        uses: crate-ci/typos@master
      - name: Lint
        uses: golangci/golangci-lint-action@v7
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Build
        run: go build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ttx
          path: ttx
